package com.elega9t.elixir.gui.components.config.ui.lnf;

import com.elega9t.commons.swing.config.ConfigPanel;

import javax.swing.*;

/**
 *
 * @author dev
 */
public class LookAndFeelConfigPanel extends ConfigPanel {

    /**
     * Creates new form LookAndFeelConfigPanel
     */
    public LookAndFeelConfigPanel() {
        super("UI", "Look'N'Feel");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lookAndFeelConfigPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lookAndFeelComboBox = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.GridLayout(0, 1));

        lookAndFeelConfigPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));

        jLabel1.setText("Look And Feel: ");
        lookAndFeelConfigPanel.add(jLabel1);

        lookAndFeelComboBox.setModel(new DefaultComboBoxModel());
        lookAndFeelConfigPanel.add(lookAndFeelComboBox);

        add(lookAndFeelConfigPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox lookAndFeelComboBox;
    private javax.swing.JPanel lookAndFeelConfigPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initConfig() {
        final String currentLookAndFeel = UIManager.getLookAndFeel().getName();
        final UIManager.LookAndFeelInfo[] installedLookAndFeels = UIManager.getInstalledLookAndFeels();
        final DefaultComboBoxModel model = (DefaultComboBoxModel) lookAndFeelComboBox.getModel();
        for (UIManager.LookAndFeelInfo installedLookAndFeel : installedLookAndFeels) {
            final LookAndFeelEntity lookAndFeelEntity = new LookAndFeelEntity(installedLookAndFeel);
            model.addElement(lookAndFeelEntity);
            if(currentLookAndFeel == installedLookAndFeel.getName()) {
                model.setSelectedItem(lookAndFeelEntity);
            }
        }
    }
    
    @Override
    public void applyConfigChange(java.awt.Container parent, java.awt.event.ActionEvent evt) {
        try {
            final DefaultComboBoxModel model = (DefaultComboBoxModel) lookAndFeelComboBox.getModel();
            LookAndFeelEntity lookAndFeel = (LookAndFeelEntity) model.getSelectedItem();
            UIManager.setLookAndFeel(lookAndFeel.getLnfClassName());
            SwingUtilities.updateComponentTreeUI(parent);
            SwingUtilities.updateComponentTreeUI(this);
            SwingUtilities.updateComponentTreeUI((java.awt.Component)evt.getSource());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
}
