/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.elixir.gui.components;

import com.elega9t.commons.swing.BackgroundText;

import java.awt.Graphics;

import static com.elega9t.commons.swing.util.SwingUtilities.paintBackgroundText;

public class TextBackgroundPanel extends javax.swing.JPanel {
    
    private final BackgroundText[] backgroundText;

    /**
     * Creates new form TextBackgroundPanel
     */
    public TextBackgroundPanel(BackgroundText... text) {
        initComponents();
        this.backgroundText = text;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    protected void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        paintBackgroundText(graphics, getFont(), getHeight(), getWidth(), backgroundText);
    }
    
}
