package com.elega9t.elixir.gui.components;

import javax.swing.tree.TreeNode;

public class ConnectionsPanel extends javax.swing.JPanel {
    
    private TreeNode connectionsRoot;

    /**
     * Creates new form ConnectionsPanel
     */
    public ConnectionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionsTreeScrollPane = new javax.swing.JScrollPane();
        connectionsTree = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        connectionsTree.setModel(new javax.swing.tree.DefaultTreeModel(connectionsRoot));
        connectionsTreeScrollPane.setViewportView(connectionsTree);

        add(connectionsTreeScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree connectionsTree;
    private javax.swing.JScrollPane connectionsTreeScrollPane;
    // End of variables declaration//GEN-END:variables
}
