/*
 * The MIT License
 *
 * Copyright 2013 yogesh.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.elega9t.elixir.gui.components;

/**
 *
 * @author yogesh
 */
public class ResultsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultsTabbedPane = new javax.swing.JTabbedPane();
        resultDataPanel = new javax.swing.JPanel();
        resultDataScrollPane = new javax.swing.JScrollPane();
        resultDataTable = new javax.swing.JTable() {

            public boolean getScrollableTracksViewportWidth() {
                return getPreferredSize().width < getParent().getWidth();
            }

        };
        messagesPanel = new javax.swing.JPanel();
        messagesScrollPane = new javax.swing.JScrollPane();
        messagesTextPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        resultDataPanel.setLayout(new java.awt.BorderLayout());

        resultDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultDataTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        resultDataScrollPane.setViewportView(resultDataTable);

        resultDataPanel.add(resultDataScrollPane, java.awt.BorderLayout.CENTER);

        resultsTabbedPane.addTab("Data", resultDataPanel);

        messagesPanel.setLayout(new java.awt.BorderLayout());

        messagesScrollPane.setViewportView(messagesTextPane);

        messagesPanel.add(messagesScrollPane, java.awt.BorderLayout.CENTER);

        resultsTabbedPane.addTab("Messages", messagesPanel);

        add(resultsTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JScrollPane messagesScrollPane;
    private javax.swing.JTextPane messagesTextPane;
    private javax.swing.JPanel resultDataPanel;
    private javax.swing.JScrollPane resultDataScrollPane;
    private javax.swing.JTable resultDataTable;
    private javax.swing.JTabbedPane resultsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
