/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.gui.platform.components;

/**
 *
 * @author yogesh
 */
public class EventProgressPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventProgressPanel
     */
    public EventProgressPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventLabel = new javax.swing.JLabel();
        eventProgressBar = new javax.swing.JProgressBar();
        stopLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        setLayout(new java.awt.BorderLayout(10, 0));

        eventLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/platform/icons/wait.gif"))); // NOI18N
        eventLabel.setText("blah blha blah");
        eventLabel.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/platform/icons/wait_disabled.png"))); // NOI18N
        add(eventLabel, java.awt.BorderLayout.LINE_START);
        add(eventProgressBar, java.awt.BorderLayout.CENTER);

        stopLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/platform/icons/stop.png"))); // NOI18N
        add(stopLabel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setEnabled(boolean enabled) {
        eventLabel.setEnabled(enabled);
        if(!enabled) {
            eventLabel.setText(null);
        }
        eventProgressBar.setVisible(enabled);
        stopLabel.setVisible(enabled);
        if(getParent() != null) {
            getParent().validate();
            getParent().doLayout();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventLabel;
    private javax.swing.JProgressBar eventProgressBar;
    private javax.swing.JLabel stopLabel;
    // End of variables declaration//GEN-END:variables
}
