/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.gui.platform.components;

import com.elega9t.gui.platform.mgr.log.LogEvent;
import com.elega9t.gui.platform.mgr.log.LogListener;
import com.elega9t.gui.platform.mgr.log.LogManager;

import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author yogesh
 */
public class LogsManagerPanel extends javax.swing.JPanel implements LogListener {

    /**
     * Creates new form LogsManagerPanel
     */
    public LogsManagerPanel() {
        initComponents();
        LogManager.getInstance().addLogListener(LogManager.ALL_LOG_LISTENER, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logsManagerScrollPane = new javax.swing.JScrollPane();
        logsManagerTextPane = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        logsManagerScrollPane.setViewportView(logsManagerTextPane);

        add(logsManagerScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void log(LogEvent event) {
        Document document = logsManagerTextPane.getDocument();
        try {
            document.insertString(document.getLength(), event.getLog(), null);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane logsManagerScrollPane;
    private javax.swing.JTextPane logsManagerTextPane;
    // End of variables declaration//GEN-END:variables
}
