/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.elixir.gui.components.config.keymap;

import com.elega9t.commons.swing.JTitle;
import com.elega9t.commons.swing.KeyStrokeEditor;
import com.elega9t.commons.swing.config.ConfigDialog;
import com.elega9t.elixir.gui.ResourceStrings;

import javax.swing.*;
import java.awt.*;

public class EditKeyStrokeDialog extends javax.swing.JDialog {

    private KeyStrokeInfo keyStrokeInfo;

    public EditKeyStrokeDialog(Dialog dialog, KeyStrokeInfo keyStrokeInfo, boolean modal) {
        super(dialog, modal);
        this.keyStrokeInfo = new KeyStrokeInfo(keyStrokeInfo);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secondKeyStrokeCheckBox = new javax.swing.JCheckBox();
        bodyPanel = new javax.swing.JPanel();
        firstKeyStrokeTitlePanel = new JTitle(new javax.swing.JLabel("First KeyStroke"));
        firstKeyStrokeBeforeFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        firstKeyStrokePanel = new javax.swing.JPanel();
        keyStrokeTextField = new KeyStrokeEditor();
        firstKeyStrokeAfterFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        secondKeyStrokeTitlePanel = new JTitle(secondKeyStrokeCheckBox);
        secondKeyStrokeBeforeFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        secondKeyStrokePanel = new javax.swing.JPanel();
        secondKeyStrokeTextField = new KeyStrokeEditor();
        secondKeyStrokeAfterFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        conflictsTitlePanel = new JTitle(new javax.swing.JLabel("Conflicts"));
        conflictsInfoBeforeFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        conflictsInfoPanel = new javax.swing.JPanel();
        conflictInfoScrollPane = new javax.swing.JScrollPane();
        conflictInfoTextArea = new javax.swing.JTextArea();
        conflictsInfoAfterFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        buttonsPanel = new javax.swing.JPanel();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        secondKeyStrokeCheckBox.setSelected(keyStrokeInfo.secondKeyStroke != null);
        secondKeyStrokeCheckBox.setText("Second KeyStroke");
        secondKeyStrokeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondKeyStrokeCheckBoxActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Keyboard Shortcut");
        setSize(new java.awt.Dimension(255, 330));

        bodyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 0, 5));
        bodyPanel.setLayout(new javax.swing.BoxLayout(bodyPanel, javax.swing.BoxLayout.PAGE_AXIS));
        bodyPanel.add(firstKeyStrokeTitlePanel);
        bodyPanel.add(firstKeyStrokeBeforeFiller);

        firstKeyStrokePanel.setLayout(new java.awt.BorderLayout());

        keyStrokeTextField.setText(keyStrokeInfo.keyStroke != null ? keyStrokeInfo.keyStroke.toString() : "");
        firstKeyStrokePanel.add(keyStrokeTextField, java.awt.BorderLayout.CENTER);

        bodyPanel.add(firstKeyStrokePanel);
        bodyPanel.add(firstKeyStrokeAfterFiller);
        bodyPanel.add(secondKeyStrokeTitlePanel);
        bodyPanel.add(secondKeyStrokeBeforeFiller);

        secondKeyStrokePanel.setLayout(new java.awt.BorderLayout());

        secondKeyStrokeTextField.setText(keyStrokeInfo.secondKeyStroke != null ? keyStrokeInfo.secondKeyStroke.toString() : "");
        secondKeyStrokePanel.add(secondKeyStrokeTextField, java.awt.BorderLayout.CENTER);

        bodyPanel.add(secondKeyStrokePanel);
        bodyPanel.add(secondKeyStrokeAfterFiller);
        bodyPanel.add(conflictsTitlePanel);
        bodyPanel.add(conflictsInfoBeforeFiller);

        conflictsInfoPanel.setLayout(new java.awt.BorderLayout());

        conflictInfoScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        conflictInfoTextArea.setColumns(20);
        conflictInfoTextArea.setRows(5);
        conflictInfoScrollPane.setViewportView(conflictInfoTextArea);

        conflictsInfoPanel.add(conflictInfoScrollPane, java.awt.BorderLayout.CENTER);

        bodyPanel.add(conflictsInfoPanel);
        bodyPanel.add(conflictsInfoAfterFiller);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        applyButton.setText(ResourceStrings.buttons.getString("apply"));
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(applyButton);

        cancelButton.setText(ResourceStrings.buttons.getString("cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelButton);

        bodyPanel.add(buttonsPanel);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        keyStrokeInfo.keyStroke = ((KeyStrokeEditor)keyStrokeTextField).getKeyStroke();
        if(secondKeyStrokeCheckBox.isSelected()) {
            keyStrokeInfo.secondKeyStroke = ((KeyStrokeEditor)secondKeyStrokeTextField).getKeyStroke();
        } else {
            keyStrokeInfo.secondKeyStroke = null;
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void secondKeyStrokeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondKeyStrokeCheckBoxActionPerformed
        secondKeyStrokeTextField.setEnabled(secondKeyStrokeCheckBox.isSelected());
    }//GEN-LAST:event_secondKeyStrokeCheckBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        keyStrokeInfo = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public static KeyStrokeInfo showDialog(ConfigDialog parent, KeyStrokeInfo keyStrokeInfo) {
        EditKeyStrokeDialog dialog = new EditKeyStrokeDialog(parent, keyStrokeInfo, true);
        dialog.setVisible(true);
        return dialog.keyStrokeInfo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane conflictInfoScrollPane;
    private javax.swing.JTextArea conflictInfoTextArea;
    private javax.swing.Box.Filler conflictsInfoAfterFiller;
    private javax.swing.Box.Filler conflictsInfoBeforeFiller;
    private javax.swing.JPanel conflictsInfoPanel;
    private javax.swing.JPanel conflictsTitlePanel;
    private javax.swing.Box.Filler firstKeyStrokeAfterFiller;
    private javax.swing.Box.Filler firstKeyStrokeBeforeFiller;
    private javax.swing.JPanel firstKeyStrokePanel;
    private javax.swing.JPanel firstKeyStrokeTitlePanel;
    private javax.swing.JTextField keyStrokeTextField;
    private javax.swing.Box.Filler secondKeyStrokeAfterFiller;
    private javax.swing.Box.Filler secondKeyStrokeBeforeFiller;
    private javax.swing.JCheckBox secondKeyStrokeCheckBox;
    private javax.swing.JPanel secondKeyStrokePanel;
    private javax.swing.JTextField secondKeyStrokeTextField;
    private javax.swing.JPanel secondKeyStrokeTitlePanel;
    // End of variables declaration//GEN-END:variables

    public static class KeyStrokeInfo {
        
        private KeyStroke keyStroke;
        private KeyStroke secondKeyStroke;

        public KeyStrokeInfo(KeyStrokeInfo keyStrokeInfo) {
            this(keyStrokeInfo.getKeyStroke(), keyStrokeInfo.getSecondKeyStroke());
        }

        public KeyStrokeInfo(KeyStroke keyStroke, KeyStroke secondKeyStroke) {
            this.keyStroke = keyStroke;
            this.secondKeyStroke = secondKeyStroke;
        }

        public KeyStroke getKeyStroke() {
            return keyStroke;
        }

        public KeyStroke getSecondKeyStroke() {
            return secondKeyStroke;
        }

    }
    
}
