/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.gui.platform.dock;

import com.elega9t.gui.platform.dock.DockButton.Location;

/**
 *
 * @author yogesh
 */
public class DockPanel extends javax.swing.JPanel {

    /**
     * Creates new form DockPanel
     */
    public DockPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftDockPanel = new javax.swing.JPanel();
        jPanel1 = new DockButton(Location.LEFT, "Hi");
        rightDockPanel = new javax.swing.JPanel();
        jPanel2 = new DockButton(Location.RIGHT, "Hi");
        bottomDockPanel = new javax.swing.JPanel();
        jPanel3 = new DockButton(Location.BOTTOM, "Hi");
        bodyPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        leftDockPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 1)));
        leftDockPanel.setLayout(new javax.swing.BoxLayout(leftDockPanel, javax.swing.BoxLayout.PAGE_AXIS));
        leftDockPanel.add(jPanel1);

        add(leftDockPanel, java.awt.BorderLayout.LINE_START);

        rightDockPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 1)));
        rightDockPanel.setLayout(new javax.swing.BoxLayout(rightDockPanel, javax.swing.BoxLayout.PAGE_AXIS));
        rightDockPanel.add(jPanel2);

        add(rightDockPanel, java.awt.BorderLayout.LINE_END);

        bottomDockPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(0, 0, 1, 1)));
        bottomDockPanel.setLayout(new javax.swing.BoxLayout(bottomDockPanel, javax.swing.BoxLayout.LINE_AXIS));
        bottomDockPanel.add(jPanel3);

        add(bottomDockPanel, java.awt.BorderLayout.PAGE_END);

        bodyPanel.setLayout(new java.awt.BorderLayout(5, 5));
        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bottomDockPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel leftDockPanel;
    private javax.swing.JPanel rightDockPanel;
    // End of variables declaration//GEN-END:variables
}
