/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.elixir.gui.form;

import com.elega9t.elixir.gui.mgr.IconsManager;

import java.awt.event.ActionListener;

/**
 *
 * @author yogesh
 */
public class CloseTabPanel extends javax.swing.JPanel {

    /**
     * Creates new form CloseTabPanel
     */
    public CloseTabPanel() {
        initComponents();
    }
    
    public void setTitle(String title) {
        titleLabel.setText(title);
    }
    
    public void addActionListener(ActionListener actionListener) {
        closeButton.addActionListener(actionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());
        add(titleLabel, java.awt.BorderLayout.CENTER);

        closeButton.setIcon(IconsManager.getInstance().system.getCloseIcon());
        closeButton.setBorderPainted(false);
        closeButton.setFocusable(false);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.setPreferredSize(new java.awt.Dimension(16, 16));
        add(closeButton, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
