package com.elega9t.elixir.gui.form;

import com.elega9t.commons.swing.GuiEntityListCellRenderer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class EditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditorPanel
     */
    public EditorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorSplitPane = new javax.swing.JSplitPane();
        topPanel = new javax.swing.JPanel();
        topPanelToolbarPanel = new javax.swing.JPanel();
        queryPanelToolBar = new javax.swing.JToolBar();
        executeQueryButton = new javax.swing.JButton();
        currentDatabaseToolBar = new javax.swing.JToolBar();
        currentDatabaseComboBox = new javax.swing.JComboBox();
        queryEditorScrollPane = new javax.swing.JScrollPane();
        queryEditorPane = new javax.swing.JEditorPane();
        bottomPanel = new javax.swing.JPanel();
        resultsTabbedPane = new javax.swing.JTabbedPane();
        resultTablePanel = new javax.swing.JPanel();
        resultTableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        messagesPanel = new javax.swing.JPanel();
        messagesScrollPane = new javax.swing.JScrollPane();
        messagesTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        editorSplitPane.setDividerLocation(300);
        editorSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topPanel.setLayout(new java.awt.BorderLayout());

        topPanelToolbarPanel.setLayout(new java.awt.BorderLayout());

        queryPanelToolBar.setFloatable(false);
        queryPanelToolBar.setRollover(true);

        executeQueryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/elixir/gui/icons/execute_query.png"))); // NOI18N
        executeQueryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        executeQueryButton.setFocusable(false);
        executeQueryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        executeQueryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        queryPanelToolBar.add(executeQueryButton);

        topPanelToolbarPanel.add(queryPanelToolBar, java.awt.BorderLayout.LINE_START);

        currentDatabaseToolBar.setFloatable(false);
        currentDatabaseToolBar.setRollover(true);

        currentDatabaseComboBox.setModel(new DefaultComboBoxModel());
        currentDatabaseComboBox.setRenderer(new GuiEntityListCellRenderer());
        currentDatabaseToolBar.add(currentDatabaseComboBox);

        topPanelToolbarPanel.add(currentDatabaseToolBar, java.awt.BorderLayout.LINE_END);

        topPanel.add(topPanelToolbarPanel, java.awt.BorderLayout.PAGE_START);

        queryEditorScrollPane.setViewportView(queryEditorPane);

        topPanel.add(queryEditorScrollPane, java.awt.BorderLayout.CENTER);

        editorSplitPane.setTopComponent(topPanel);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        resultTablePanel.setLayout(new java.awt.BorderLayout());

        resultTable.setModel(new DefaultTableModel());
        resultTableScrollPane.setViewportView(resultTable);

        resultTablePanel.add(resultTableScrollPane, java.awt.BorderLayout.CENTER);

        resultsTabbedPane.addTab("Results", resultTablePanel);

        messagesPanel.setLayout(new java.awt.BorderLayout());

        messagesTextArea.setColumns(20);
        messagesTextArea.setRows(5);
        messagesScrollPane.setViewportView(messagesTextArea);

        messagesPanel.add(messagesScrollPane, java.awt.BorderLayout.CENTER);

        resultsTabbedPane.addTab("Messages", messagesPanel);

        bottomPanel.add(resultsTabbedPane, java.awt.BorderLayout.CENTER);

        editorSplitPane.setRightComponent(bottomPanel);

        add(editorSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JComboBox currentDatabaseComboBox;
    private javax.swing.JToolBar currentDatabaseToolBar;
    private javax.swing.JSplitPane editorSplitPane;
    private javax.swing.JButton executeQueryButton;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JScrollPane messagesScrollPane;
    private javax.swing.JTextArea messagesTextArea;
    private javax.swing.JEditorPane queryEditorPane;
    private javax.swing.JScrollPane queryEditorScrollPane;
    private javax.swing.JToolBar queryPanelToolBar;
    private javax.swing.JTable resultTable;
    private javax.swing.JPanel resultTablePanel;
    private javax.swing.JScrollPane resultTableScrollPane;
    private javax.swing.JTabbedPane resultsTabbedPane;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topPanelToolbarPanel;
    // End of variables declaration//GEN-END:variables
}
