/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.elixir.gui.form;

import com.elega9t.commons.entity.GuiEntityNode;
import com.elega9t.commons.swing.BackgroundText;
import com.elega9t.commons.swing.GuiEntityNodeTreeCellRenderer;
import com.elega9t.elixir.gui.ResourceStrings;
import com.elega9t.elixir.gui.components.TextBackgroundSplitPane;
import com.elega9t.elixir.gui.dialog.ConnectToDatabaseDialog;

import javax.swing.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.util.List;

public class Main extends javax.swing.JFrame {

    private GuiEntityNode savedConnections = new GuiEntityNode(ResourceStrings.main.getString("saved.connections"), new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/elixir/gui/icons/saved_database_connections.png")), ResourceStrings.main.getString("saved.connections.tooltip"));
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        toolBar = new javax.swing.JToolBar();
        connectToDatabaseToolBarButton = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        bodySplitPane = new javax.swing.JSplitPane();
        rightBasePanel = new javax.swing.JPanel();
        editorTabbedPane = new TextBackgroundSplitPane(
            new BackgroundText(ResourceStrings.main.getString("title"), 100, 30).bold(),
            new BackgroundText(ResourceStrings.main.getString("website"), 130, 20),
            new BackgroundText("No tabs are open", 220, 20).underlined().bold(),
            new BackgroundText("\u2023 Open Recent files with \u2318E", 255, 17),
            new BackgroundText("\u2023 Drag'n'Drop file(s) here from Finder", 280, 17).alighWithPrevious()
        );
        leftBasePanel = new javax.swing.JPanel();
        connectionsTreeScrollPane = new javax.swing.JScrollPane();
        connectionsTree = new JTree(savedConnections);
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connectToDatabaseFileMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(ResourceStrings.main.getString("title"));
        setExtendedState(MAXIMIZED_BOTH);

        topPanel.setLayout(new java.awt.BorderLayout());

        toolBar.setRollover(true);

        connectToDatabaseToolBarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/elixir/gui/icons/connect_to_database.png"))); // NOI18N
        connectToDatabaseToolBarButton.setFocusable(false);
        connectToDatabaseToolBarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connectToDatabaseToolBarButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        connectToDatabaseToolBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectToDatabaseToolBarButtonActionPerformed(evt);
            }
        });
        toolBar.add(connectToDatabaseToolBarButton);

        topPanel.add(toolBar, java.awt.BorderLayout.CENTER);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setLayout(new java.awt.BorderLayout());

        bodySplitPane.setDividerLocation(200);
        bodySplitPane.setOneTouchExpandable(true);

        rightBasePanel.setLayout(new java.awt.BorderLayout());
        rightBasePanel.add(editorTabbedPane, java.awt.BorderLayout.CENTER);
        editorTabbedPane.setDropTarget(new DropTarget() {
            public synchronized void drop(DropTargetDropEvent evt) {
                editorTabbedPaneDropEvent(evt);
            }
        });

        bodySplitPane.setRightComponent(rightBasePanel);

        leftBasePanel.setLayout(new java.awt.BorderLayout());

        connectionsTree.setCellRenderer(new GuiEntityNodeTreeCellRenderer());
        connectionsTreeScrollPane.setViewportView(connectionsTree);

        leftBasePanel.add(connectionsTreeScrollPane, java.awt.BorderLayout.CENTER);

        bodySplitPane.setLeftComponent(leftBasePanel);

        bodyPanel.add(bodySplitPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottomPanel.setLayout(new java.awt.BorderLayout());

        statusLabel.setText(ResourceStrings.main.getString("title"));
        bottomPanel.add(statusLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        fileMenu.setText(ResourceStrings.menu.getString("main.file.menu"));

        connectToDatabaseFileMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/elega9t/elixir/gui/icons/connect_to_database.png"))); // NOI18N
        connectToDatabaseFileMenuItem.setText(ResourceStrings.menu.getString("file.menu.connectToDatabase"));
        connectToDatabaseFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectToDatabaseFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connectToDatabaseFileMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText(ResourceStrings.menu.getString("main.edit.menu"));
        menuBar.add(editMenu);

        setJMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void connectToDatabaseToolBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectToDatabaseToolBarButtonActionPerformed
        connectToDatabaseFileMenuItemActionPerformed(evt);
    }//GEN-LAST:event_connectToDatabaseToolBarButtonActionPerformed

    private void connectToDatabaseFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectToDatabaseFileMenuItemActionPerformed
        new ConnectToDatabaseDialog(this, true).openDialog();
    }//GEN-LAST:event_connectToDatabaseFileMenuItemActionPerformed

    private void editorTabbedPaneDropEvent(DropTargetDropEvent evt) {
        try {
            evt.acceptDrop(DnDConstants.ACTION_COPY);
            List<File> droppedFiles = (List<File>)
                evt.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
            for (File file : droppedFiles) {
                editorTabbedPane.addTab(file.getName(), new JPanel());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JSplitPane bodySplitPane;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JMenuItem connectToDatabaseFileMenuItem;
    private javax.swing.JButton connectToDatabaseToolBarButton;
    private javax.swing.JTree connectionsTree;
    private javax.swing.JScrollPane connectionsTreeScrollPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JTabbedPane editorTabbedPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel leftBasePanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel rightBasePanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
