/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.docking;

import java.awt.*;

public class DockButtonHolderPanel extends javax.swing.JPanel {

    /**
     * Creates new form DockButtonHolderPanel
     */
    public DockButtonHolderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public java.awt.Dimension getPreferredSize() {
        if(isVisible()) {
            return super.getPreferredSize();
        } else {
            return new java.awt.Dimension(0, 0);
        }
    }

    @Override
    public boolean isVisible() {
        return super.isVisible() && getComponentCount() > 0;
    }

    public void add(Component component, DockLocation location) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
