/*
 * Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 * ELEGA9T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.Copyright (c) 2011 - 2012. Elega9t Ltd. All rights reserved.
 */

package com.elega9t.commons.swing.config;

import java.awt.*;

public class SettingsBreadcrumbPanel extends javax.swing.JPanel {

    /**
     * Creates new form SettingsBreadcrumbPanel
     */
    public SettingsBreadcrumbPanel() {
        initComponents();
        breadcrumbLabel.setFont(new Font(breadcrumbLabel.getFont().getFontName(), Font.BOLD, breadcrumbLabel.getFont().getSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breadcrumbLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        breadcrumbLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(breadcrumbLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breadcrumbLabel;
    // End of variables declaration//GEN-END:variables

    public void setBreadcrumb(String... path) {
        StringBuilder breadcrumbBuilder = new StringBuilder("    ");
        for(int index=0; index<path.length; index++) {
            breadcrumbBuilder.append(path[index]);
            if(index < path.length - 1) {
                breadcrumbBuilder.append(" ").append('\u2023').append(" ");
            }
        }
        breadcrumbLabel.setText(breadcrumbBuilder.toString());
    }

    @Override
    protected void paintComponent(Graphics graphics) {
        ((Graphics2D)graphics).setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
        ((Graphics2D)graphics).setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        super.paintComponent(graphics);
        graphics.setColor(new Color(0x00, 0x99, 0xCC));
        graphics.fillRoundRect(0, 0, getWidth(), getHeight() + 10, 20, 20);
    }

}
